export const dashboardData = {
  kpis: {
    totalProperties: {
      value: 847,
      change: +12.5,
      trend: "up",
      period: "vs last month",
    },
    totalEarnings: {
      value: 18450000,
      change: +18.2,
      trend: "up",
      period: "vs last month",
      currency: "USD",
    },
    activeListing: {
      value: 342,
      change: +8.7,
      trend: "up",
      period: "vs last month",
    },
    totalViews: {
      value: 125670,
      change: +25.3,
      trend: "up",
      period: "vs last month",
    },
    conversionRate: {
      value: 4.2,
      change: +0.8,
      trend: "up",
      period: "vs last month",
      suffix: "%",
    },
    averagePrice: {
      value: 15850000,
      change: +5.2,
      trend: "up",
      period: "vs last month",
      currency: "USD",
    },
  },
  earningsData: [
    { month: "Jan", earnings: 1180000, properties: 15, views: 8500 },
    { month: "Feb", earnings: 1410000, properties: 18, views: 9200 },
    { month: "Mar", earnings: 1295000, properties: 16, views: 8800 },
    { month: "Apr", earnings: 1645000, properties: 21, views: 10900 },
    { month: "May", earnings: 1875000, properties: 24, views: 12200 },
    { month: "Jun", earnings: 2120000, properties: 28, views: 14600 },
    { month: "Jul", earnings: 1985000, properties: 26, views: 13400 },
    { month: "Aug", earnings: 2350000, properties: 31, views: 16900 },
    { month: "Sep", earnings: 2680000, properties: 35, views: 18500 },
    { month: "Oct", earnings: 2925000, properties: 38, views: 20200 },
    { month: "Nov", earnings: 2790000, properties: 36, views: 19800 },
    { month: "Dec", earnings: 3120000, properties: 42, views: 22400 },
  ],
  propertyCategories: [
    { name: "Luxury Estates", value: 285, percentage: 42.1, color: "#2563eb" },
    { name: "Beachfront", value: 198, percentage: 29.2, color: "#3b82f6" },
    { name: "Penthouses", value: 156, percentage: 18.4, color: "#60a5fa" },
    { name: "Commercial", value: 71, percentage: 10.3, color: "#93c5fd" },
  ],
  propertyStatus: [
    { name: "Available", value: 342, color: "#2563eb" },
    { name: "Under Contract", value: 125, color: "#3b82f6" },
    { name: "Sold", value: 89, color: "#60a5fa" },
  ],
  topProperties: [
    {
      id: 1,
      title: "Modern Hillside Estate",
      location: "Beverly Hills, CA",
      price: 24900000,
      views: 2250,
      inquiries: 42,
      status: "Available",
      beds: 7,
      baths: 9,
      sqft: 12500,
    },
    {
      id: 2,
      title: "Contemporary Beachfront Villa",
      location: "Malibu, CA",
      price: 17500000,
      views: 1985,
      inquiries: 35,
      status: "Under Contract",
      beds: 5,
      baths: 7,
      sqft: 8200,
    },
    {
      id: 3,
      title: "Architectural Masterpiece",
      location: "Hollywood Hills, CA",
      price: 12750000,
      views: 1756,
      inquiries: 28,
      status: "Available",
      beds: 6,
      baths: 8,
      sqft: 9800,
    },
    {
      id: 4,
      title: "Oceanfront Penthouse",
      location: "Santa Monica, CA",
      price: 19500000,
      views: 2156,
      inquiries: 38,
      status: "Available",
      beds: 4,
      baths: 6,
      sqft: 7500,
    },
  ],
  recentActivities: [
    {
      id: 1,
      type: "sale",
      title: "Property Sold",
      description: "Beverly Hills Estate sold for $24.9M",
      time: "2 hours ago",
      icon: "TrendingUp",
      color: "text-blue-600",
    },
    {
      id: 2,
      type: "inquiry",
      title: "High-Value Inquiry",
      description: "Client interested in Malibu Beachfront Villa",
      time: "4 hours ago",
      icon: "MessageSquare",
      color: "text-blue-600",
    },
    {
      id: 3,
      type: "listing",
      title: "New Luxury Listing",
      description: "Penthouse in Santa Monica listed at $19.5M",
      time: "6 hours ago",
      icon: "Plus",
      color: "text-blue-600",
    },
  ],
  locationPerformance: [
    {
      location: "Beverly Hills",
      properties: 125,
      avgPrice: 22100000,
      totalViews: 35600,
    },
    {
      location: "Malibu",
      properties: 98,
      avgPrice: 18900000,
      totalViews: 28400,
    },
    {
      location: "Hollywood Hills",
      properties: 89,
      avgPrice: 14650000,
      totalViews: 24900,
    },
    {
      location: "Santa Monica",
      properties: 76,
      avgPrice: 16850000,
      totalViews: 21700,
    },
    {
      location: "Bel Air",
      properties: 54,
      avgPrice: 28500000,
      totalViews: 19200,
    },
  ],
};